CREATE TABLE client_profiles
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    profile_picture_url     VARCHAR(255),
    nickname                VARCHAR(255),
    age                     INTEGER,
    location                VARCHAR(255),
    therapy_goals           VARCHAR(255),
    preferred_communication VARCHAR(255),
    user_id                 BIGINT,
    CONSTRAINT pk_client_profiles PRIMARY KEY (id)
);

CREATE TABLE therapist_profiles
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    profile_picture_url VARCHAR(255),
    full_name           VARCHAR(255),
    title               VARCHAR(255),
    bio                 VARCHAR(255),
    experience_years    INTEGER,
    credentials         VARCHAR(255),
    specialties         VARCHAR(255),
    user_id             BIGINT,
    CONSTRAINT pk_therapist_profiles PRIMARY KEY (id)
);

ALTER TABLE client_profiles
    ADD CONSTRAINT uc_client_profiles_user UNIQUE (user_id);

ALTER TABLE therapist_profiles
    ADD CONSTRAINT uc_therapist_profiles_user UNIQUE (user_id);

ALTER TABLE client_profiles
    ADD CONSTRAINT FK_CLIENT_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE therapist_profiles
    ADD CONSTRAINT FK_THERAPIST_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
